version: '2'
services:
  jumbo-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/jumbo/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jumbo
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
